# Generated by Django 4.2.6 on 2023-11-02 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='noteBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookTitle', models.CharField(max_length=100)),
                ('bookDescription', models.TextField()),
                ('image', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='notesPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentNote', models.TextField()),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('noteBookId', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='notesPagesB', to='notes.notebook')),
            ],
        ),
    ]
